In [599]:
import pandas as pd
import numpy as np
import re 
import json
import datetime as dt

In [600]:
data = pd.read_json('data.json')
df = data.copy()
df.dtypes

Intitulé du poste      object
Date de publication    object
lieu                   object
competences            object
Type de poste          object
dtype: object

In [601]:
df.shape

(230, 5)

In [602]:
df = df.replace('\n','', regex=True)
df['Intitulé du poste'] = [' '.join(item).replace('\n', '').lower() for item in df['Intitulé du poste']]
df['lieu'] = [', '.join(item).replace('\n', '').lower() for item in df['lieu']]
df['competences'] = [' '.join(item).replace('\n', '').replace(' ', ', ').lower() for item in df['competences']]
df['Type de poste'] = [''.join(item).replace('\n', ', ').replace(', , ', '').lower().strip() for item in df['Type de poste']]
# df[['lieu', 'salary']] = df["lieu"].str.split(",", expand = True, n=1)

In [603]:
y = [' '.join(element.split()) for element in df['Date de publication']]

['postée il y a 21 jours',
 'postée il y a 1 mois',
 'postée il y a 27 jours',
 'postée il y a 21 jours',
 'postée il y a 3 jours',
 'postée il y a 15 jours',
 'postée il y a 28 jours',
 'postée il y a 1 mois',
 'postée il y a 12 heures',
 'postée il y a 13 jours',
 'postée il y a 13 jours',
 'postée il y a 14 jours',
 'postée il y a 3 jours',
 'postée il y a 14 jours',
 'postée il y a 28 jours',
 'postée il y a 9 jours',
 'postée il y a 2 jours',
 'postée il y a 2 jours',
 'postée il y a 14 jours',
 'postée il y a 5 jours',
 'postée il y a 22 jours',
 'postée il y a 8 heures',
 'postée il y a 25 jours',
 'postée il y a 21 jours',
 'postée il y a 29 jours',
 'postée il y a 19 jours',
 'postée hier',
 'postée il y a 1 mois',
 'postée hier',
 'postée il y a 5 jours',
 'postée il y a 14 jours',
 'postée il y a 13 jours',
 'postée il y a 9 jours',
 'postée il y a 22 jours',
 'postée il y a 21 jours',
 'postée il y a 9 jours',
 'postée il y a 22 jours',
 'postée il y a 22 jours',
 'postée il y a 29 jours',
 'postée hier',
 'postée il y a 7 jours',
 'postée il y a 22 jours',
 'postée il y a 2 jours',
 'postée il y a 17 jours',
 'postée il y a 2 jours',
 'postée il y a 21 jours',
 'postée il y a 22 jours',
 'postée il y a 9 jours',
 'postée il y a 22 jours',
 'postée il y a 15 jours',
 'postée il y a 1 mois',
 'postée il y a 15 jours',
 'postée il y a 20 jours',
 'postée il y a 21 jours',
 'postée il y a 20 jours',
 'postée il y a 28 jours',
 'postée il y a 20 jours',
 'postée il y a 22 jours',
 'postée il y a 24 jours',
 'postée il y a 1 mois',
 'postée il y a 21 jours',
 'postée il y a 1 mois',
 'postée il y a 27 jours',
 'postée il y a 21 jours',
 'postée il y a 3 jours',
 'postée il y a 15 jours',
 'postée il y a 28 jours',
 'postée il y a 1 mois',
 'postée il y a 12 heures',
 'postée il y a 13 jours',
 'postée il y a 13 jours',
 'postée il y a 14 jours',
 'postée il y a 3 jours',
 'postée il y a 14 jours',
 'postée il y a 28 jours',
 'postée il y a 9 jours',
 'postée il y a 2 jours',
 'postée il y a 2 jours',
 'postée il y a 14 jours',
 'postée il y a 5 jours',
 'postée il y a 9 jours',
 'postée il y a 14 heures',
 'postée il y a 22 jours',
 'postée il y a 9 jours',
 'postée il y a 24 jours',
 'postée il y a 24 jours',
 'postée il y a 4 jours',
 'postée il y a 6 jours',
 'postée il y a 2 jours',
 'postée il y a 24 jours',
 'postée il y a 7 jours',
 'postée il y a 21 jours',
 'postée il y a 1 mois',
 'postée il y a 17 jours',
 'postée il y a 11 jours',
 'postée hier',
 'postée il y a 22 jours',
 'postée hier',
 'postée hier',
 'postée il y a 5 jours',
 'postée il y a 27 jours',
 'postée il y a 7 jours',
 'postée hier',
 'postée il y a 1 mois',
 'postée hier',
 'postée il y a 16 jours',
 'postée il y a 20 jours',
 'postée il y a 13 jours',
 'postée hier',
 'postée hier',
 'postée il y a 3 heures',
 'postée il y a 1 mois',
 'postée il y a 3 jours',
 'postée il y a 28 jours',
 'postée il y a 16 jours',
 'postée il y a 2 jours',
 'postée il y a 17 jours',
 'postée il y a 17 jours',
 'postée il y a 1 mois',
 'postée il y a 1 mois',
 'postée il y a 27 jours',
 'postée il y a 1 mois',
 'postée il y a 22 jours',
 'postée il y a 1 mois',
 'postée il y a 22 jours',
 'postée il y a 3 jours',
 'postée il y a 3 jours',
 'postée il y a 3 jours',
 'postée il y a 10 jours',
 'postée il y a 22 jours',
 'postée il y a 17 jours',
 'postée il y a 1 mois',
 'postée il y a 14 jours',
 'postée il y a 17 jours',
 'postée il y a 25 jours',
 'postée il y a 17 jours',
 'postée il y a 27 jours',
 'postée il y a 24 jours',
 'postée il y a 7 jours',
 'postée hier',
 'postée il y a 3 jours',
 'postée il y a 3 jours',
 'postée il y a 1 mois',
 'postée il y a 14 jours',
 'postée il y a 3 jours',
 'postée il y a 27 jours',
 'postée il y a 3 jours',
 'postée il y a 20 jours',
 'postée il y a 1 mois',
 'postée hier',
 'postée il y a 21 jours',
 'postée il y a 27 jours',
 'postée il y a 20 jours',
 'postée il y a 21 jours',
 'postée il y a 17 jours',
 'postée il y a 9 jours',
 'postée hier',
 'postée il y a 1 mois',
 'postée il y a 21 jours',
 'postée il y a 2 heures',
 'postée il y a 16 jours',
 'postée il y a 1 mois',
 'postée il y a 1 mois',
 'postée hier',
 'postée il y a 24 jours',
 'postée il y a 27 jours',
 'postée il y a 17 jours',
 'postée il y a 7 jours',
 'postée il y a 1 mois',
 'postée il y a 25 jours',
 'postée il y a 28 jours',
 'postée il y a 10 jours',
 'postée il y a 13 jours',
 'postée il y a 2 heures',
 'postée il y a 3 jours',
 'postée il y a 17 jours',
 'postée il y a 1 mois',
 'postée il y a 22 jours',
 'postée il y a 6 jours',
 'postée il y a 17 jours',
 'postée il y a 1 mois',
 'postée il y a 14 jours',
 'postée il y a 28 jours',
 'postée il y a 21 jours',
 'postée il y a 13 jours',
 'postée il y a 6 jours',
 'postée il y a 10 jours',
 'postée il y a 17 jours',
 'postée il y a 28 jours',
 'postée il y a 17 jours',
 'postée il y a 8 jours',
 'postée il y a 14 jours',
 'postée il y a 20 jours',
 'postée il y a 20 jours',
 'postée il y a 14 jours',
 'postée il y a 3 heures',
 'postée il y a 13 jours',
 'postée il y a 13 jours',
 'postée il y a 10 jours',
 'postée il y a 14 jours',
 'postée il y a 2 jours',
 'postée il y a 22 jours',
 'postée il y a 16 jours',
 'postée il y a 22 jours',
 'postée il y a 21 jours',
 'postée hier',
 'postée il y a 13 jours',
 'postée il y a 22 jours',
 'postée il y a 1 mois',
 'postée il y a 22 jours',
 'postée il y a 14 jours',
 'postée il y a 22 jours',
 'postée il y a 22 jours',
 'postée il y a 21 jours',
 'postée il y a 23 jours',
 'postée il y a 14 jours',
 'postée il y a 22 jours',
 'postée il y a 14 jours',
 'postée il y a 14 jours',
 'postée il y a 3 jours',
 'postée il y a 17 jours',
 'postée il y a 17 jours',
 'postée il y a 14 jours',
 'postée il y a 2 heures',
 'postée il y a 13 jours',
 'postée il y a 27 jours',
 'postée il y a 3 jours',
 'postée il y a 2 heures',
 'postée il y a 16 jours',
 'postée il y a 3 jours']

In [604]:
date0 = dt.date(2023, 1, 15)
dates = []
for item in y:
    delai = item.split()
    if delai[-1] == "jours":
        delta = dt.timedelta(days=int(delai[-2]))
        date = date0 - delta
        dates.append(date)
    elif delai[-1] == 'mois':
        delta = dt.timedelta(weeks=4*int(delai[-2]))
        date = date0 - delta
        dates.append(date)
    elif delai[-1] == 'heures':
        delta = dt.timedelta(hours=int(delai[-2]))
        date = date0 - delta
        dates.append(date)
    elif delai[-1] == 'hier':
        date = dt.date(2013, 1, 14)
        dates.append(date)
df['Date de publication'] = dates
df

,Intitulé du poste,Date de publication,lieu,competences,Type de poste
0,data analyst - publicité,2022-12-25,paris,"sql, t-sql, outils","sept lieues sas, cabinet de recrutement, cdi -..."
1,data analyst - h/f,2022-12-18,"paris, la défense","support, outils, agile, design, big, data","edf france, client final, cdi - temps plein,"
2,customer data analyst (h/f),2022-12-19,paris,"crm, data, quality, sql, sas, python","hermès, client final, cdi - temps plein,"
3,master data analyst h/f,2022-12-25,moussy-le-vieux,"si, support, sap","tereos, client final, cdi - temps plein,"
4,portfolio data analyst h/f,2023-01-12,france,"outils, support, decisionnel, sql, test","safran-group, client final, cdi - temps plein,"
...,...,...,...,...,...
225,sap fiori developer (h/f),2022-12-19,saint-ouen,"sap, abap, progiciel, système, support","groupe engie, client final, cdi - temps plein,"
226,engie digital - architecte données (h/f),2023-01-12,paris,"digital, outils, securité, sécurité, t-sql","groupe engie, client final, cdi - temps plein,"
227,quality assurance - lead qa - lead acceptance h/f,2023-01-15,boulogne-billancourt,"test, serveur, jquery, mobile, tdd","francaise des jeux, client final, cdi - temps ..."
228,data scientist,2022-12-30,"neuilly sur seine, 38.000,00 € - 50.000,00 € / an","nosql, unix, java, machine, learning, linux","beezen, esn, cdi - temps plein,"
229,datascientist (h/f),2023-01-12,saint-ouen,"big, data, support, python, réseaux, securité","groupe engie, client final, cdi - temps plein,"

In [605]:
postes = df['Intitulé du poste'].replace(to_replace='-', value='', regex=True).replace(to_replace='[(h/f)]', value='', regex=True)
postes

0                           data analyst  publicité
1                                    data analyst
2                            customer data analyst
3                              master data analyst
4                            portolio data analyst
                           ...
225                             sap iori developer
226               engie digital  arcitecte données
227    quality assurance  lead qa  lead acceptance
228                                  data scientist
229                                  datascientist
Name: Intitulé du poste, Length: 230, dtype: object

In [606]:
df.to_csv('clean_data.csv')